### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by gr2m** [schustafa/gh-pairing-with#4]
Hey :wave:

I tried using your extension today, but unfortunately am getting this error:

```
gh pairing-with gr2m
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.cli()
        github.com/schustafa/gh-pairing-with/main.go:105 +0x5b8
main.main()
        github.com/schustafa/gh-pairing-with/main.go:48 +0x7c
```

Let me know if there is anyway I can help to debug

**Comment by gr2m** [comment]
Ohh it worked after running

```
gh auth refresh --scopes user:email,read:user
```

Yay!

Maybe the error message could be improved?

**Comment by schustafa** [comment]
Thanks for this report! The next release should be a bit more friendly when this comes up.

**Comment by gr2m** [comment]
Maybe it would be worth checking the user's scopes? You can send a request to `GET /` and read out the `x-oauth-scopes` response header, that way you can fail with confidence and tell exactly what scopes are set for the current token and what scopes are missing
